export const ADD_PLAN_TEMPLATE = 'ADD_PLAN_TEMPLATE';
export const SET_PLAN_TEMPLATE_LIST = 'SET_PLAN_TEMPLATE_LIST';
export const SET_PLAN_TEMPLATE = 'SET_PLAN_TEMPLATE';

export const GET_PLAN_TEMPLATE_LIST = 'GET_PLAN_TEMPLATE_LIST'
export const SUCCESS_GET_PLAN_TEMPLATE_LIST = 'SUCCESS_GET_PLAN_TEMPLATE_LIST'
export const FAILURE_GET_PLAN_TEMPLATE_LIST = 'FAILURE_GET_PLAN_TEMPLATE_LIST'

export const SUCESS_POST_PLAN_TEMPLATE = 'SUCESS_POST_PLAN_TEMPLATE'
export const FAILURE_POST_PLAN_TEMPLATE = 'FAILURE_POST_PLAN_TEMPLATE'
